class ASStartPageConstants:
    URL = "https://automatenspielex.com/"

    HEADING_H1_XPATH = ".//h1[contains(.,'Automatenspiele Kostenlos Spielen')]"
    HEADING_H2_XPATH = ".//h2[@id='Spielen_Sie_mit_unseren_Spielautomaten']"
    HEADER_LOGO_XPATH = ".//div[@class='header__logo']"
    FOOTER_BZGA_XPATH = ".//img[@title='BZgA']"
    SYNDICATE_CASINO_SPIELEN_XPATH = ".//span[@id='top-3-btn-1']"
    HEADER_SEARCH_BUTTON_XPATH = ".//div[@class='search-btn']"
    SORT_SEARCH_BUTTON_XPATH = ".//input[@id='slots-search-input']"
    AM_BELIEBTESTEN_SORT_XPATH = ".//*/div[text()='Am Beliebtesten']"
    ALLE_SPIELE_FILTER_XPATH = ".//*/div[text()='Alle Spiele']"
    ALLE_ANBIETER_FILTER_XPATH = ".//*/div[text()='Alle Anbieter']"
    FILTER_RESET_XPATH = ".//button[@id='slots-reset-btn']"
    MEGA_JOKER_QUICK_LINK = ".//*/span[text()='Mega Joker']"
    EMAIL_FOOTER_XPATH = ".//a[@class='footer_email']"
    COUNT_SPIELE_XPATH = ".//div[@id='slots-count']"
    NEXT_PAGE_PAGINATION_XPATH = ".//span[@class='next page-numbers']"
    TAG_A = "a"
    FIRST_MENU_ITEM_HREF = "href"
    INPUT_FIELD_XPATH = ".//input[@class='searchform__input']"
    SEARCH_VALUE_TEXT = "qwerty"
    NOTHING_FOUND_XPATH = ".//h2[@class='not_found']"
    AMOUNT_OF_SLOTS_XPATH = ".//div[@id='slots-count']"
    LINK_TO_PAGE_CASINO_XPATH = "//*[@id='sub-header-lg']/div/div[3]/div/div/ul/li[1]/figure/a"
    SEARCH_IN_FILTER_BLOCK_VALUE_TEXT = "Book of Ra"
    FIND_SLOT_XPATH = "/html/body/div/div[2]/div/div/main/div[5]/div/a/figure/figcaption/span"
    UP_TO_TOP_BUTTON_XPATH = ".//div[@id='scroller']"

